import React from "react";
import { Typography } from "tabler-react-2";
const { H3, H4, Text } = Typography;

export const switchForHighlight = (highlighted) => {
  switch (highlighted) {
    case "orglegalname":
      return (
        <>
          <H3>Legal organization name</H3>
          <Text>
            This is the name of your organization as it appears on legal
            documents and forms. It is what your organization is legally
            registered as. This name will be public and visible to all users in
            blanket agreements put forward to your users, and in copyright
            information for your content.
          </Text>
          <Text>
            When required by law, this is the primary name that will be used to
            identify your organization. This name should be unique and not
            infringe on any existing trademarks or copyrights.
          </Text>
        </>
      );
    case "tin":
      return (
        <>
          <H3>Tax Information</H3>
          <Text>
            EIN (Employer Identification Number) or other relevant tax ID for
            the organization.
          </Text>
          <Text>
            This will never be shared with users and is encrypted at rest and in
            transit. This information is used to verify your organization's
            legal status and to ensure that you are a legitimate organization
            should issues or disputes arise.
          </Text>
        </>
      );
    case "orgtype":
      return (
        <>
          <H3>Organization Type</H3>
          <Text>
            This is the type of organization you are registering. This should
            match the legal status of your organization. If you are unregistered
            or unsure, please select "Other".
          </Text>
        </>
      );
    case "address":
      return (
        <>
          <H3>Address of Registration</H3>
          <Text>
            This is the address where your organization is registered. This
            address should match the address on your legal documents and forms.
            It should be a physical address where your organization can be
            reached.
          </Text>
          <Text>
            You can choose to show this address to the public or to keep it
            private. If it is public, it will be included in autogenerated
            marketing and contact exchanges with users, web pages, and other
            places.
          </Text>
        </>
      );
    case "legalcontact":
      return (
        <>
          <H3>Legal Contact Email</H3>
          <Text>
            This is the email address where we can reach your organization's for
            legal purposes. This email address may be used to send legal
            notices, updates to our terms of service, and other important legal
            information.
          </Text>
        </>
      );

    default:
      return (
        <>
          <H3>Information</H3>
          <Text>
            These fields may be confusing. When you hover over a field, we will
            provide you with more information about what it is, why we need it,
            and what we recommend you provide.
          </Text>
        </>
      );
  }
};
