import React from "react";
import { Typography } from "tabler-react-2";
const { H3, H4, Text } = Typography;

export const switchForHighlight = (highlighted) => {
  switch (highlighted) {
    case "mainbannerimg":
      return (
        <>
          <H3>Main Banner Image</H3>
          <Text>
            This is the main image that will be displayed on your organization's
            page. It should be a high-quality image that represents your
            organization well. We recommend using an image that is at least 1920
            pixels wide. We will resize the image to be a max of 1920x1080. This
            is similar to what you might have as a cover photo on a social media
            platform like Twitter or Linkedin.
          </Text>
          <Text>
            This image may be used in various places on your organization's
            profile site, in emails, and in other autogenerated marketing
            materials. It is important that this image is high-quality and
            represents your organization well.
          </Text>
        </>
      );
    case "mainlogoimg":
      return (
        <>
          <H3>Main Logo Image</H3>
          <Text>
            This is the main logo that will be displayed on your organization's
            page. It should be a high-quality image that represents your
            organization well. We recommend using an image that is at least 400
            pixels wide. We will resize the image to be a max of 800x400.
          </Text>
          <Text>
            This image may be used in various places on your organization's
            profile site, in emails, and in other autogenerated marketing
            materials. It is important that this image is high-quality and
            represents your organization well.
          </Text>
        </>
      );
    case "squarelogoimg":
      return (
        <>
          <H3>Square Logo Image</H3>
          <Text>
            This is the square logo that will be displayed on your
            organization's page. It should be a high-quality image that
            represents your organization well. We recommend using an image that
            is at least 400 pixels wide. We will resize the image to be a max of
            400x400. This will be used for favicons, icons, profile images, and
            other places where a square image is needed.
          </Text>
          <Text>
            We do not enforce a square aspect ratio, but we recommend it. If you
            do not provide a square image, we cannot guarantee that it will be
            displayed correctly in all places.
          </Text>
        </>
      );
    default:
      return (
        <>
          <H3>Information</H3>
          <Text>
            These fields may be confusing. When you hover over a field, we will
            provide you with more information about what it is, why we need it,
            and what we recommend you provide.
          </Text>
        </>
      );
  }
};
