import React from "react";
import { Typography } from "tabler-react-2";
const { H3, H4, Text } = Typography;

export const switchForHighlight = (highlighted) => {
  switch (highlighted) {
    case "orgname":
      return (
        <>
          <H3>Organization name</H3>
          <Text>
            This is the name of your organization that will be displayed to the
            public. It will be on your public profile, any events you create,
            public-facing marketing content, and communcations through our
            platform.
          </Text>
          <Text>
            If you go by a different name than your legal name, you can enter
            the one that you want to be known by here. There will be space later
            on to enter legal details on your organization.
          </Text>
          <Text>
            You can change this later, but public visibility of existing content
            may be affected.
          </Text>
        </>
      );
    case "orgwebsite":
      return (
        <>
          <H3>Organization website</H3>
          <Text>
            If you have a website for your organization, you can enter it here.
            This will be displayed and linked on your public profile and any
            events you create. This will also be used in any marketing content
            that you create, and in autogenerated communications with your event
            contacts.
          </Text>
          <Text>
            You can change this later, but public visibility of existing content
            may be affected if you do not configure forwarding or redirection.
            We will provide you with resources and best practices if you ever
            decide to edit your website URL.
          </Text>
        </>
      );
    case "publicemail":
      return (
        <>
          <H3>Public Contact Email</H3>
          <Text>
            This is the email address that the public can use to contact your
            organization. This will be displayed on your public profile and any
            events you create. This will also be used in any marketing content
            that you create, and in autogenerated communications with your event
            contacts. We will direct your event contacts to this email address
            if they have questions or need to reach out to you regarding
            anything about the event.
          </Text>
          <Text>
            You will be able to configure additional, more specific contact
            emails later on as you populate your events. We will always pick the
            most relevant and specific contact email for a given event.
          </Text>
        </>
      );
    case "privatemail":
      return (
        <>
          <H3>Private Contact Email</H3>
          <Text>
            This is the email address that EventPilot will use to contact you.
            We will not display this email address to the public, and we will
            not provide it to event contacts. This email address will be used
            for account verification, password resets, and other administrative
            communications, as well as communications from our team.
          </Text>
          <Text>
            It is important that you provide an email address that you check
            regularly, as we will use this email address to communicate with you
            about important updates, changes, and other information about your
            events.
          </Text>
          <Text>
            We will not use this email address for marketing purposes, and we
            will not provide it to third parties except as required by law.
          </Text>
        </>
      );
    case "phonenum":
      return (
        <>
          <H3>Private Contact Phone</H3>
          <Text>
            This is the phone number that EventPilot will use to contact you. We
            will not display this phone number to the public, and we will not
            provide it to event contacts. This phone number will be used for
            urgent administrative communications. When possible, we will use
            email, but in some cases with large events, we may need to contact
            you quickly, so will attempt to do so by phone.
          </Text>
          <Text>
            If calls to this phone number do not go through, we may elect to
            reach out via phone to members of your team, but the phone number
            provided here will always be our first step.
          </Text>
        </>
      );
    case "category":
      return (
        <>
          <H3>Category</H3>
          <Text>
            This is the category that best describes your organization. This is
            a broad category that will be used to help us understand your
            organization and its mission. This will be displayed on your public
            profile and any events you create. We will use this information for
            internal analytics, and to help us cater future features and tools
            to your needs.
          </Text>
          <Text>
            <H4>Political Advocacy Organization</H4>
            Political Advocacy Organizations work to influence government
            policy, legislation, and elections. These organizations may engage
            in lobbying, voter education, or political campaigns.
          </Text>
          <Text>
            <H4>Environmental Organization</H4>
            Environmental Organizations focus on protecting natural ecosystems
            and promoting sustainable practices. Their efforts often include
            conservation, pollution reduction, and climate change advocacy.
          </Text>
          <Text>
            <H4>Service-based Organization</H4>
            Service-based Organizations provide direct aid or essential services
            to communities in need. This can include food distribution, housing,
            healthcare, or other forms of social assistance.
          </Text>
          <Text>
            <H4>Arts & Culture Organization</H4>
            Arts & Culture Organizations promote artistic expression, cultural
            heritage, and creative education. They may operate galleries,
            theaters, museums, or sponsor cultural events.
          </Text>
          <Text>
            <H4>Educational Organization</H4>
            Educational Organizations work to improve access to education and
            learning resources. They often provide scholarships, fund schools,
            or create educational programs for various age groups.
          </Text>
          <Text>
            <H4>Health-related Organization</H4>
            Health-related Organizations aim to improve public health through
            research, education, and direct medical services. They may focus on
            disease prevention, treatment, or healthcare access.
          </Text>
          <Text>
            <H4>Religious Organization</H4>
            Religious Organizations are centered around faith-based activities,
            spiritual education, and community outreach. They often provide
            support services to their members and engage in charitable work.
          </Text>
          <Text>
            <H4>International Organization</H4>
            International Organizations focus on global issues like poverty,
            disease, and humanitarian crises. Their efforts span across
            countries, providing aid, development, and relief in various
            regions.
          </Text>
          <Text>
            <H4>Animal Welfare Organization</H4>
            Animal Welfare Organizations work to protect animals, advocate for
            their rights, and promote wildlife conservation. They may operate
            shelters, rescues, or engage in public awareness campaigns.
          </Text>
          <Text>
            <H4>Foundation & Grant-Making Organization</H4>
            Foundations & Grant-Making Organizations fund other initiatives,
            organizations, or causes. Their primary goal is to provide financial
            support to promote various philanthropic efforts.
          </Text>
          <Text>
            <H4>Youth Development Organization</H4>
            Youth Development Organizations aim to provide education,
            mentorship, and leadership opportunities for young people. They
            often offer programs in schools, after-school activities, or camps.
          </Text>
          <Text>
            <H4>Social Justice Organization</H4>
            Social Justice Organizations advocate for equality, human rights,
            and fairness. They work to address issues like discrimination,
            inequality, and civil liberties through advocacy and legal support.
          </Text>
        </>
      );
    default:
      return (
        <>
          <H3>Information</H3>
          <Text>
            These fields may be confusing. When you hover over a field, we will
            provide you with more information about what it is, why we need it,
            and what we recommend you provide.
          </Text>
        </>
      );
  }
};
